export interface Question {
  id: string
  section: string
  sectionIcon: string
  required: boolean
  question: string
  hint: string
  placeholder: string
  type: 'text' | 'textarea' | 'multi-collect'
  collectMin?: number
  collectMax?: number
  collectPrompt?: string
  collectDonePrompt?: string
}

export const questions: Question[] = [
  {
    id: 'nickname',
    section: '基本信息',
    sectionIcon: '👋',
    required: true,
    question: '你希望粉丝怎么叫你？',
    hint: '昵称、小名、X姐、X哥都行',
    placeholder: '输入你的昵称...',
    type: 'text',
  },
  {
    id: 'age_city',
    section: '基本信息',
    sectionIcon: '👋',
    required: true,
    question: '年龄和所在城市？',
    hint: '',
    placeholder: '比如：28岁，杭州',
    type: 'text',
  },
  {
    id: 'relationship',
    section: '生活与家庭',
    sectionIcon: '🏠',
    required: true,
    question: '你现在的情感状态是？',
    hint: '已婚 / 未婚 / 恋爱中 / 离异 / 丁克 / 不婚主义 / 想做情侣号……都可以说',
    placeholder: '输入你的情感状态...',
    type: 'text',
  },
  {
    id: 'kids',
    section: '生活与家庭',
    sectionIcon: '🏠',
    required: true,
    question: '有小孩吗？几个、多大？',
    hint: '没有也直接写"没有"就行',
    placeholder: '输入...',
    type: 'text',
  },
  {
    id: 'parents',
    section: '生活与家庭',
    sectionIcon: '🏠',
    required: true,
    question: '和父母的关系怎么样？用一两句话说说。',
    hint: '比如"关系很好，我妈是我最好的朋友" / "一般，不太联系" / "从小被管很严，现在在和解"——怎么真实怎么来',
    placeholder: '输入...',
    type: 'textarea',
  },
  // === 野心评估 ===
  {
    id: 'streaming_frequency',
    section: '野心评估',
    sectionIcon: '🔥',
    required: true,
    question: '你现在的直播频率是怎么样的？一周几次、每次多久？',
    hint: '如实说就行，我们不是要听"我以后会每天播"，而是想知道你现在的真实状态',
    placeholder: '比如：一周3次，每次2小时...',
    type: 'textarea',
  },
  {
    id: 'relocation',
    section: '野心评估',
    sectionIcon: '🔥',
    required: true,
    question: '能接受搬家到北京/杭州/广州吗？',
    hint: '如果你已经在这些城市就直接说。不能搬也没关系，如实说',
    placeholder: '输入...',
    type: 'textarea',
  },
  {
    id: 'daily_schedule',
    section: '野心评估',
    sectionIcon: '🔥',
    required: true,
    question: '你现在每天的时间大概怎么安排的？从早到晚说说。',
    hint: '比如：早上9点起床，上午处理XX，下午做XX，晚上直播到XX点',
    placeholder: '从早到晚大概说说...',
    type: 'textarea',
  },
  // === 人品评估 ===
  {
    id: 'last_job_ending',
    section: '人品评估',
    sectionIcon: '🤝',
    required: true,
    question: '你上一份工作或合作是怎么结束的？',
    hint: '比如合同到期、主动离职、被裁、合伙散了……怎么真实怎么说',
    placeholder: '输入...',
    type: 'textarea',
  },
  {
    id: 'money_split',
    section: '人品评估',
    sectionIcon: '🤝',
    required: true,
    question: '有没有跟人合伙或合作分钱的经历？最后怎么处理的？',
    hint: '没有也直接写"没有"。有的话说说过程和结果',
    placeholder: '输入...',
    type: 'textarea',
  },
  {
    id: 'unfair_experience',
    section: '人品评估',
    sectionIcon: '🤝',
    required: true,
    question: '有没有一次你觉得被不公平对待的经历？你当时怎么做的？',
    hint: '工作上的、生活上的都行，重点是你怎么处理的',
    placeholder: '输入...',
    type: 'textarea',
  },
  {
    id: 'never_cooperate',
    section: '人品评估',
    sectionIcon: '🤝',
    required: true,
    question: '你觉得什么样的人你绝对不会合作？',
    hint: '比如不守信用的、爱甩锅的、太计较的……说说你的底线',
    placeholder: '输入...',
    type: 'textarea',
  },
  // === 职业经历 ===
  {
    id: 'one_sentence',
    section: '职业经历',
    sectionIcon: '💼',
    required: true,
    question: '用一句话介绍你自己——你会怎么跟陌生人说？',
    hint: '不是简历，是你自己觉得最能代表你的一句话',
    placeholder: '输入你的一句话介绍...',
    type: 'textarea',
  },
  {
    id: 'career_path',
    section: '职业经历',
    sectionIcon: '💼',
    required: true,
    question: '你的职业路线是什么？做过什么、怎么走到今天的？',
    hint: '比如：大学学的XX → 毕业做了XX → 后来转行做XX → 现在在做XX',
    placeholder: '输入你的职业经历...',
    type: 'textarea',
  },
  {
    id: 'unique_experiences',
    section: '独特经历 ★★★ 最重要',
    sectionIcon: '⭐',
    required: true,
    question: '说 1-3 件你经历过的、大多数人没经历过的事。先说第一件！',
    hint: '这是整份表最重要的一题。花过大钱的、踩过大坑的、人生转折的、别人觉得不可思议的——都算。\n\n举几个例子帮你打开思路：\n• "花了XX万做了XX，发现完全没用"\n• "XX岁裸辞/离婚/创业，所有人都觉得我疯了"\n• "得过一个很少见的病，后来自己折腾好了"\n• "去过一个很冷门的地方，做了一件很冒险的事"\n• "在某个行业干了X年，见过别人看不到的内幕"',
    placeholder: '先说第一件事...',
    type: 'multi-collect',
    collectMin: 1,
    collectMax: 3,
    collectPrompt: '好的，记下了！还有没有？再想想有没有其他特别的经历？（没有了就输入"没了"）',
    collectDonePrompt: '好的，这些经历非常有价值！',
  },
  {
    id: 'speaking_style',
    section: '个性与表达',
    sectionIcon: '🗣️',
    required: true,
    question: '你说话最大的特点是什么？举一句你经常说的话或口头禅。',
    hint: '比如"我说话比较直"——然后举例："我经常跟朋友说别想了，干就完了"',
    placeholder: '特点 + 口头禅...',
    type: 'textarea',
  },
  {
    id: 'never_say',
    section: '个性与表达',
    sectionIcon: '🗣️',
    required: true,
    question: '有没有你绝对不会说的话、绝对不想做的内容？',
    hint: '比如"我绝对不卖惨" / "不想做擦边" / "不想装专家" / "讨厌说教"',
    placeholder: '输入你的底线...',
    type: 'textarea',
  },
  {
    id: 'credentials',
    section: '特殊背书与资质',
    sectionIcon: '🏆',
    required: false,
    question: '有没有什么很厉害的证书、头衔、或者听起来就让人"哇"的背景？',
    hint: '不一定是传统意义的"厉害"，是那种别人听了会记住的。比如：\n• 名校学历（哈佛MBA、清华、央美……）\n• 特殊执照（飞行执照、潜水教练、品酒师……）\n• 行业头衔（某品牌前高管、某领域第一批从业者……）\n• 媒体经历（上过XX节目、和XX合作过……）\n• 数据成绩（卖过XX亿、粉丝XX万……）\n\n没有也完全没关系，跳过就行。',
    placeholder: '输入或跳过...',
    type: 'textarea',
  },
  {
    id: 'content_direction',
    section: '内容方向',
    sectionIcon: '🎬',
    required: false,
    question: '你想靠什么让观众记住你？',
    hint: '比如：踩过的坑、专业知识、生活方式、搞笑人设、真实不装、毒舌点评……',
    placeholder: '输入...',
    type: 'textarea',
  },
  {
    id: 'target_audience',
    section: '内容方向',
    sectionIcon: '🎬',
    required: false,
    question: '你最想影响什么样的人？她们/他们通常在什么时候会刷到你的内容？',
    hint: '比如"25-35岁的职场女性，下班后刷手机的时候" / "宝妈，带娃间隙看看"',
    placeholder: '输入...',
    type: 'textarea',
  },
  {
    id: 'liked_blogger',
    section: '内容方向',
    sectionIcon: '🎬',
    required: false,
    question: '有没有你喜欢的博主？请给出 ta 的抖音号（或抖音主页链接），并说说喜欢 ta 什么、不喜欢 ta 什么？',
    hint: '我们会自动分析这个博主的内容风格，帮你找到适合你的参考方向。\n\n比如："抖音号 XXX，喜欢她说话很真实不装，不喜欢她有时候太啰嗦"',
    placeholder: '抖音号/链接 + 喜欢什么 + 不喜欢什么...',
    type: 'textarea',
  },
  {
    id: 'liked_douyin_content',
    section: '加分项',
    sectionIcon: '🌟',
    required: false,
    question: '发 1-3 条你在全抖音上最喜欢的视频链接——就是那种"我好想做出这种内容"的视频。',
    hint: '我们会分析这些内容的共同特点，帮你找到内容方向。一条一条发就行，发完一条我会问你下一条。',
    placeholder: '粘贴第一条抖音链接...',
    type: 'multi-collect',
    collectMin: 1,
    collectMax: 3,
    collectPrompt: '收到！还有没有下一条？（没有了就输入"没了"）',
    collectDonePrompt: '好的，这些参考内容很有价值！',
  },
  {
    id: 'own_best_content',
    section: '加分项',
    sectionIcon: '🌟',
    required: false,
    question: '发 1-3 条你自己账号上最满意的视频链接。',
    hint: '我们会从你自己的内容里提取说话风格和内容调性，这比填100个问题都有用。一条一条发就行。',
    placeholder: '粘贴第一条抖音链接...',
    type: 'multi-collect',
    collectMin: 1,
    collectMax: 3,
    collectPrompt: '收到！还有没有下一条？（没有了就输入"没了"）',
    collectDonePrompt: '好的！',
  },
]

// AI transition messages between sections
export const sectionTransitions: Record<string, string> = {
  '基本信息': '先来认识一下你吧～',
  '生活与家庭': '好的！接下来聊聊你的生活～',
  '野心评估': '接下来几个问题很重要，我们想了解你对这件事的投入程度 🔥',
  '人品评估': '好的！再聊几个关于合作和相处的问题～',
  '职业经历': '了解了！再来说说你的职业经历～',
  '独特经历 ★★★ 最重要': '接下来是最重要的部分了！你经历过的那些独特的事，是人设的核心素材 ⭐',
  '个性与表达': '快完成了！聊聊你的说话风格和个性～',
  '特殊背书与资质': '下面几题是选填的，有就填，没有跳过也完全OK～',
  '内容方向': '再聊聊你的内容想法～',
  '加分项': '最后几题！这些是加分项～',
}
